### ISSUE TITLE
Source for your entries?

### ISSUE THREAD

**Issue by beerisgood** [crssi/BlockLists#1]
Is your blocklist based on some lists or self-made? If so, where did you get these mainly ?

**Comment by crssi** [comment]
Hi @beerisgood, it is self-made... spotted those myself.

Those come from my Deny list: https://github.com/crssi/Firefox/blob/master/uBO-Deny.txt

I goes years back, even before I have made a github account.

Oh... and this list is now included in OISD list too.

Cheers

**Comment by beerisgood** [comment]
All right!

So, using OISD cover yours already and you recommend their list anyway.
Thanks for fast answer! Question solved 🍺
